import express from 'express';import cors from 'cors';import helmet from 'helmet';import morgan from 'morgan';import crypto from 'node:crypto';import http from 'node:http';import {WebSocketServer} from 'ws';
import {env} from './config.js';import {requireEdgeAuth} from './middlewares/serviceAuth.js';import {redisRateLimit} from './middlewares/rateLimiter.js';import {log} from './utils/logger.js';import {enqueueMediaJob,mediaEvents} from './queue/bullQueue.js';import {createUploadUrl,objectKey,createDownloadUrl} from './services/r2Storage.js';import {translateSubtitle} from './services/vietsubAi.js';import {redis} from './services/redis.js';import {initDatabase,updateJob,saveJob,pgPool} from './db/postgres.js';import {adminRouter} from './routes/admin.js';
const app=express();app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:env.CORS_ORIGIN.split(',').map(x=>x.trim()),credentials:true}));app.use(morgan('combined'));app.use(express.json({limit:'10mb'}));app.use(redisRateLimit(120,60));
app.get('/health',async(_req,res)=>{res.json({ok:true,service:'vietsub-backend',version:'3.0.0',redis:(await redis.ping())==='PONG',postgres:!!pgPool,time:new Date().toISOString()})});
app.post('/api/v1/uploads/presign',async(req,res)=>{const {userId='anonymous',projectId='default',fileName,contentType='application/octet-stream'}=req.body??{};if(!fileName)return res.status(400).json({error:'fileName_required'});res.json({key:objectKey(userId,projectId,fileName),url:await createUploadUrl(objectKey(userId,projectId,fileName),contentType)})});
app.post('/api/v1/jobs',async(req,res)=>{const b=req.body??{};const jobId=String(b.jobId??crypto.randomUUID());const payload={jobId,type:b.type,userId:String(b.userId??'anonymous'),projectId:b.projectId,inputPath:b.inputPath,outputPath:b.outputPath,subtitleFile:b.subtitleFile,text:b.text,targetLanguage:b.targetLanguage,url:b.url};await saveJob({id:jobId,userId:payload.userId,projectId:payload.projectId,type:payload.type,status:'QUEUED',payload});const job=await enqueueMediaJob(payload as any);res.status(202).json({jobId:job.id,status:'QUEUED'});});
app.use('/api/v1/admin',adminRouter);
app.get('/api/v1/jobs/:id',async(req,res)=>{if(!pgPool)return res.json({jobId:req.params.id,status:'UNKNOWN'});const r=await pgPool.query('SELECT * FROM media_jobs WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'not_found'});res.json(r.rows[0])});
app.get('/api/v1/download',async(req,res)=>{const key=String(req.query.key??'');if(!key)return res.status(400).json({error:'key_required'});res.json({url:await createDownloadUrl(key)})});
app.post('/api/v1/ai/translate',async(req,res)=>{const {text,targetLanguage='vi'}=req.body??{};if(typeof text!=='string')return res.status(400).json({error:'text_required'});res.json({text:await translateSubtitle(text,targetLanguage)})});
app.post('/api/v1/edge/callback',requireEdgeAuth,async(req,res)=>{const id=String(req.body?.jobId??'');if(id)await updateJob(id,{status:String(req.body.status??'RUNNING'),progress:Number(req.body.progress??0),result:req.body.result,error:req.body.error});res.json({ok:true})});
const server=http.createServer(app);const wss=new WebSocketServer({noServer:true});const clients=new Map<string,Set<any>>();function broadcast(jobId:string,msg:any){for(const ws of clients.get(jobId)??[])if(ws.readyState===1)ws.send(JSON.stringify(msg))}
server.on('upgrade',(req,socket,head)=>{const u=new URL(req.url??'',`http://${req.headers.host}`);if(u.pathname!=='/ws/jobs'){socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>{const jobId=u.searchParams.get('jobId')??'';if(!clients.has(jobId))clients.set(jobId,new Set());clients.get(jobId)!.add(ws);ws.send(JSON.stringify({type:'connected',jobId}));ws.on('close',()=>clients.get(jobId)?.delete(ws));});});
mediaEvents.on('progress',({jobId,data})=>broadcast(String(jobId),{type:'progress',jobId,progress:data}));mediaEvents.on('completed',({jobId})=>broadcast(String(jobId),{type:'completed',jobId}));mediaEvents.on('failed',({jobId,failedReason})=>broadcast(String(jobId),{type:'failed',jobId,error:failedReason}));
await initDatabase();server.listen(env.PORT,()=>log.info('api.started',{port:env.PORT,ws:'/ws/jobs'}));
